# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-24T01:29:25+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Account(BaseModel):
    created_at: datetime = Field(
        ..., description='ISO 8601 timestamp of created time.', title='Created At'
    )
    link_token_id: Optional[UUID] = Field(
        None, description='UUID of the link token.', title='Link Token Id'
    )
    platform_id: UUID = Field(
        ...,
        description='UUID of the platform associated with this account.',
        title='Platform Id',
    )
    id: UUID = Field(..., description='Unique identifier for the object.', title='Id')
