# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-24T01:33:56+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Country(Enum):
    US = 'US'


class Address(BaseModel):
    raw: str = Field(..., description='The raw address.', title='Raw')
    line1: Optional[str] = Field(
        None, description='The first line of the address.', title='Line1'
    )
    line2: Optional[str] = Field(
        None, description='The second line of the address.', title='Line2'
    )
    city: Optional[str] = Field(
        None, description='The city of the address.', title='City'
    )
    state: Optional[str] = Field(
        None, description='The state of the address.', title='State'
    )
    postal_code: Optional[str] = Field(
        None, description='The postal code of the address.', title='Postal Code'
    )
    country: Optional[Country] = Field(
        None, description='The country of the address.', title='Country'
    )
