# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-24T01:35:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Category(Enum):
    retirement = 'retirement'
    medical_insurance = 'medical_insurance'
    hsa = 'hsa'
    fsa = 'fsa'
    dental = 'dental'
    vision = 'vision'
    life_insurance = 'life_insurance'
    disability = 'disability'
    child_support = 'child_support'
    commuter = 'commuter'
    union_dues = 'union_dues'
    other = 'other'


class Type(Enum):
    pre_tax = 'pre_tax'
    post_tax = 'post_tax'
    unknown = 'unknown'


class Deduction(BaseModel):
    name: str = Field(..., description='The name of the deduction.', title='Name')
    category: Category = Field(
        ..., description='The category of deduction.', title='Category'
    )
    amount: int = Field(..., description='The amount of deduction.', title='Amount')
    type: Type = Field(..., description='The type of deduction.', title='Type')
