# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-24T01:30:04+00:00

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Currency(Enum):
    AED = 'AED'
    AFN = 'AFN'
    ALL = 'ALL'
    AMD = 'AMD'
    ANG = 'ANG'
    AOA = 'AOA'
    ARS = 'ARS'
    AUD = 'AUD'
    AWG = 'AWG'
    AZN = 'AZN'
    BAM = 'BAM'
    BBD = 'BBD'
    BDT = 'BDT'
    BGN = 'BGN'
    BHD = 'BHD'
    BIF = 'BIF'
    BMD = 'BMD'
    BND = 'BND'
    BOB = 'BOB'
    BOV = 'BOV'
    BRL = 'BRL'
    BSD = 'BSD'
    BTN = 'BTN'
    BWP = 'BWP'
    BYR = 'BYR'
    BZD = 'BZD'
    CAD = 'CAD'
    CDF = 'CDF'
    CHE = 'CHE'
    CHF = 'CHF'
    CHW = 'CHW'
    CLF = 'CLF'
    CLP = 'CLP'
    CNY = 'CNY'
    COP = 'COP'
    COU = 'COU'
    CRC = 'CRC'
    CUC = 'CUC'
    CUP = 'CUP'
    CVE = 'CVE'
    CZK = 'CZK'
    DJF = 'DJF'
    DKK = 'DKK'
    DOP = 'DOP'
    DZD = 'DZD'
    EGP = 'EGP'
    ERN = 'ERN'
    ETB = 'ETB'
    EUR = 'EUR'
    FJD = 'FJD'
    FKP = 'FKP'
    GBP = 'GBP'
    GEL = 'GEL'
    GHS = 'GHS'
    GIP = 'GIP'
    GMD = 'GMD'
    GNF = 'GNF'
    GTQ = 'GTQ'
    GYD = 'GYD'
    HKD = 'HKD'
    HNL = 'HNL'
    HRK = 'HRK'
    HTG = 'HTG'
    HUF = 'HUF'
    IDR = 'IDR'
    ILS = 'ILS'
    INR = 'INR'
    IQD = 'IQD'
    IRR = 'IRR'
    ISK = 'ISK'
    JMD = 'JMD'
    JOD = 'JOD'
    JPY = 'JPY'
    KES = 'KES'
    KGS = 'KGS'
    KHR = 'KHR'
    KMF = 'KMF'
    KPW = 'KPW'
    KRW = 'KRW'
    KWD = 'KWD'
    KYD = 'KYD'
    KZT = 'KZT'
    LAK = 'LAK'
    LBP = 'LBP'
    LKR = 'LKR'
    LRD = 'LRD'
    LSL = 'LSL'
    LTL = 'LTL'
    LVL = 'LVL'
    LYD = 'LYD'
    MAD = 'MAD'
    MDL = 'MDL'
    MGA = 'MGA'
    MKD = 'MKD'
    MMK = 'MMK'
    MNT = 'MNT'
    MOP = 'MOP'
    MRO = 'MRO'
    MUR = 'MUR'
    MVR = 'MVR'
    MWK = 'MWK'
    MXN = 'MXN'
    MXV = 'MXV'
    MYR = 'MYR'
    MZN = 'MZN'
    NAD = 'NAD'
    NGN = 'NGN'
    NIO = 'NIO'
    NOK = 'NOK'
    NPR = 'NPR'
    NZD = 'NZD'
    OMR = 'OMR'
    PAB = 'PAB'
    PEN = 'PEN'
    PGK = 'PGK'
    PHP = 'PHP'
    PKR = 'PKR'
    PLN = 'PLN'
    PYG = 'PYG'
    QAR = 'QAR'
    RON = 'RON'
    RSD = 'RSD'
    RUB = 'RUB'
    RWF = 'RWF'
    SAR = 'SAR'
    SBD = 'SBD'
    SCR = 'SCR'
    SDG = 'SDG'
    SEK = 'SEK'
    SGD = 'SGD'
    SHP = 'SHP'
    SLL = 'SLL'
    SOS = 'SOS'
    SRD = 'SRD'
    SSP = 'SSP'
    STD = 'STD'
    SYP = 'SYP'
    SZL = 'SZL'
    THB = 'THB'
    TJS = 'TJS'
    TMT = 'TMT'
    TND = 'TND'
    TOP = 'TOP'
    TRY = 'TRY'
    TTD = 'TTD'
    TWD = 'TWD'
    TZS = 'TZS'
    UAH = 'UAH'
    UGX = 'UGX'
    USD = 'USD'
    USN = 'USN'
    USS = 'USS'
    UYI = 'UYI'
    UYU = 'UYU'
    UZS = 'UZS'
    VEF = 'VEF'
    VND = 'VND'
    VUV = 'VUV'
    WST = 'WST'
    XAF = 'XAF'
    XAG = 'XAG'
    XAU = 'XAU'
    XBA = 'XBA'
    XBB = 'XBB'
    XBC = 'XBC'
    XBD = 'XBD'
    XCD = 'XCD'
    XDR = 'XDR'
    XOF = 'XOF'
    XPD = 'XPD'
    XPF = 'XPF'
    XPT = 'XPT'
    XTS = 'XTS'
    XXX = 'XXX'
    YER = 'YER'
    ZAR = 'ZAR'
    ZMW = 'ZMW'


class Category(Enum):
    federal_income = 'federal_income'
    social_security = 'social_security'
    medicare = 'medicare'
    state_income = 'state_income'
    local_income = 'local_income'
    other = 'other'


class Tax(BaseModel):
    name: str = Field(..., description='The name of the tax.', title='Name')
    category: Category = Field(
        ..., description='The category of tax.', title='Category'
    )
    amount: int = Field(..., description='The amount of tax.', title='Amount')


class Category1(Enum):
    retirement = 'retirement'
    medical_insurance = 'medical_insurance'
    hsa = 'hsa'
    fsa = 'fsa'
    dental = 'dental'
    vision = 'vision'
    life_insurance = 'life_insurance'
    disability = 'disability'
    child_support = 'child_support'
    commuter = 'commuter'
    union_dues = 'union_dues'
    other = 'other'


class Type(Enum):
    pre_tax = 'pre_tax'
    post_tax = 'post_tax'
    unknown = 'unknown'


class Deduction(BaseModel):
    name: str = Field(..., description='The name of the deduction.', title='Name')
    category: Category1 = Field(
        ..., description='The category of deduction.', title='Category'
    )
    amount: int = Field(..., description='The amount of deduction.', title='Amount')
    type: Type = Field(..., description='The type of deduction.', title='Type')


class Category2(Enum):
    salary = 'salary'
    hourly = 'hourly'
    overtime = 'overtime'
    double_overtime = 'double_overtime'
    premium = 'premium'
    bonus = 'bonus'
    commission = 'commission'
    tips = 'tips'
    vacation = 'vacation'
    holiday = 'holiday'
    pto = 'pto'
    sick = 'sick'
    employer_contribution = 'employer_contribution'
    other = 'other'
    fare = 'fare'


class Earning(BaseModel):
    name: str = Field(..., description='The name of the earning.', title='Name')
    category: Category2 = Field(
        ..., description='The category of earning.', title='Category'
    )
    amount: int = Field(
        ..., description='The amount of earning, in cents.', title='Amount'
    )
    rate: Optional[int] = Field(
        None, description='The amount earned per hour.', title='Rate'
    )
    hours: Optional[float] = Field(None, description='The hours worked.', title='Hours')


class Paystub(BaseModel):
    id: UUID = Field(..., description='Unique identifier for the object.', title='Id')
    created_at: datetime = Field(
        ..., description='ISO 8601 timestamp of created time.', title='Created At'
    )
    account_id: UUID = Field(
        ..., description='UUID of the payroll account.', title='Account Id'
    )
    pay_date: date = Field(
        ...,
        description='The date when the check amount is paid to the employee.',
        title='Pay Date',
    )
    pay_period_start: Optional[date] = Field(
        None,
        description='The date when the pay period begins. Some platforms, like unemployment portals, do not have fixed pay periods.',
        title='Pay Period Start',
    )
    pay_period_end: Optional[date] = Field(
        None,
        description='The date when the pay period ends. Some platforms, like unemployment portals, do not have fixed pay periods.',
        title='Pay Period End',
    )
    currency: Currency = Field(
        ...,
        description='Three-letter ISO 4217 currency code, uppercase. For example, the code for US dollars is USD.',
        title='Currency',
    )
    gross_pay_amount: int = Field(
        ...,
        description='The total earnings before any deductions are made.',
        title='Gross Pay Amount',
    )
    net_pay_amount: int = Field(
        ...,
        description='The total earnings after all taxes and deductions are removed. The equivalent of `gross_pay_amount` - `total_taxes` - `total_deductions`.',
        title='Net Pay Amount',
    )
    check_amount: int = Field(
        ...,
        description='The amount paid to the employee in this payout. Equivalent to `net_pay_amount` + `total_reimbursements`.',
        title='Check Amount',
    )
    gross_pay_ytd: Optional[int] = Field(
        None,
        description='The cumulative year to date total earnings before any taxes or deductions are removed.',
        title='Gross Pay Ytd',
    )
    net_pay_ytd: Optional[int] = Field(
        None,
        description='The cumulative year to date total earnings after all taxes and deductions are removed.',
        title='Net Pay Ytd',
    )
    total_taxes: int = Field(
        ..., description='The total taxes for this pay period.', title='Total Taxes'
    )
    total_deductions: int = Field(
        ...,
        description='The total deductions for this pay period.',
        title='Total Deductions',
    )
    total_reimbursements: int = Field(
        ...,
        description='The total reimbursements for this pay period.',
        title='Total Reimbursements',
    )
    taxes: List[Tax] = Field(
        ..., description='The taxes for this pay period.', title='Taxes'
    )
    deductions: List[Deduction] = Field(
        ..., description='The deductions for this pay period.', title='Deductions'
    )
    earnings: List[Earning] = Field(
        ..., description='The earnings for this pay period.', title='Earnings'
    )
