# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-24T01:34:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Type(Enum):
    home = 'home'
    work = 'work'
    mobile = 'mobile'


class Phone(BaseModel):
    value: str = Field(
        ..., description='The E.164 formatted phone number.', title='Value'
    )
    type: Optional[Type] = Field(
        None, description='home, mobile, work, etc.', title='Type'
    )
