# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-24T01:35:51+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class ShiftTimestamp(BaseModel):
    from_: datetime = Field(
        ...,
        alias='from',
        description='Datetime the work began. ISO 8601 format.',
        title='From',
    )
    to: datetime = Field(
        ..., description='Datetime the work ended. ISO 8601 format.', title='To'
    )
