# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-04-24T01:31:43+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Category(Enum):
    federal_income = 'federal_income'
    social_security = 'social_security'
    medicare = 'medicare'
    state_income = 'state_income'
    local_income = 'local_income'
    other = 'other'


class Tax(BaseModel):
    name: str = Field(..., description='The name of the tax.', title='Name')
    category: Category = Field(
        ..., description='The category of tax.', title='Category'
    )
    amount: int = Field(..., description='The amount of tax.', title='Amount')
